### ISSUE TITLE
exitEditMode after rebinding causes igGrid data to revert to old data

### ISSUE THREAD

**Issue by mharrington622** [IgniteUI/igniteui-angularjs#106] opened 2017-05-26 19:42 UTC
The dataSource does not appear to be getting committed after rebinding.  I found [this forum thread](https://www.infragistics.com/community/forums/t/95604.aspx) from a while ago that says to destroy the grid, but other features will be destroyed too, like selection, filtering, etc...

Steps to Reproduce:
1. Run [attached sample](https://github.com/IgniteUI/igniteui-angular/files/1032833/igGrid_AngularRows.zip).
2. Click "Load" button to assign a new datasource.
3. Enter edit mode on any cell. Do not make changes to the value.
4. Exit edit mode.

Note: In step 3, if changes are made the new data is saved correctly.

Actual Result:
The old datasource is displaying in the grid.

Expected Result:
The new datasource is displaying in the grid.

**Comment by dkamburov** [comment] 2019-02-15 13:37
@mharrington622 Unfortunately the attached sample is not available any more. Are you going to be able to re-attach it or give more details on how to reproduce this behavior?

Tried using the sample from the forum thread, but the scenario seems to be different.

From the description it sounds like an conceptual issue with the grid configuration. Using two way data binding with Angular wrappers requires setting `autoCommit: true`.

**Comment by mharrington622** [comment] 2019-02-15 15:44
@dkamburov Here's the sample again (still using 16.2). Let me know if you have any questions. [igGrid_AngularRows.zip](https://github.com/IgniteUI/igniteui-angularjs/files/2869833/igGrid_AngularRows.zip)

**Comment by dkamburov** [comment] 2019-02-18 08:44
In order to take advantage of the two way data binding for the data source, it should be bound through the attributes:
`<div data-ig-grid="gridOptions" data-source="myData" id="grid1"></div>`
It shouldn't be part of the `gridOptions`, this will allow setting `myData` and apply the change in the grid correctly.
I'm also attaching the modified sample.
[igGrid_AngularRows_mod.zip](https://github.com/IgniteUI/igniteui-angularjs/files/2874672/igGrid_AngularRows_mod.zip)

Please let me know if this helps or if you have further questions on it.

**Comment by dkamburov** [comment] 2019-02-19 13:35
@mharrington622 I'm closing this as not a bug, if you have any comments or questions, please re-open it.

**Closed by dkamburov** 2019-02-19 13:35 UTC
Labels: grid, not-a-bug, status: in-review
